# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='timeslot',
            field=models.CharField(max_length=672),
        ),
    ]
