# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0002_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AddField(
            model_name='tutorialsession',
            name='status',
            field=models.CharField(default='upcoming', max_length=10),
            preserve_default=False,
        ),
    ]
