# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0002_people2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='People2',
        ),
    ]
