# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tutorial', '0003_auto_20171022_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial.Wallet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='myuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorial.MyUser'),
        ),
        migrations.AddField(
            model_name='student',
            name='myuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorial.MyUser'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='myuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorial.MyUser'),
        ),
    ]
