# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0003_auto_20171105_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tutors',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
