# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0004_auto_20171023_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialsession',
            name='status',
            field=models.IntegerField(),
        ),
    ]
