# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0006_auto_20171111_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsession',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
