# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0006_auto_20171111_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.CharField(max_length=2000)),
            ],
        ),
    ]
