# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0007_tutorialsession_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=12)),
                ('cashflow', models.IntegerField()),
                ('type', models.IntegerField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial.TutorialSession')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial.MyUser')),
            ],
        ),
    ]
