# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0008_auto_20171121_1504'),
        ('Tutorial', '0007_tutorialsession_price'),
    ]

    operations = [
    ]
