# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0008_auto_20171121_1504'),
        ('Tutorial', '0009_auto_20171121_2041'),
    ]

    operations = [
    ]
