# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0010_merge_20171121_2148'),
        ('Tutorial', '0011_auto_20171121_2135'),
    ]

    operations = [
    ]
