# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0012_merge_20171121_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsession',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorialsession',
            name='score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
    ]
