# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0012_merge_20171121_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='showProfile',
            field=models.BooleanField(default=True),
        ),
    ]
