# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0014_mytutor'),
        ('Tutorial', '0013_tutor_showprofile'),
    ]

    operations = [
    ]
