# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0015_merge_20171122_1536'),
        ('Tutorial', '0015_merge_20171122_1638'),
    ]

    operations = [
    ]
