# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0017_myuser_image'),
        ('Tutorial', '0016_merge_20171124_1736'),
    ]

    operations = [
    ]
