# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0019_auto_20171124_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytutor',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='/static/bootstrap/images/best-rooms/1.jpg', upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='MyTutor',
        ),
    ]
