# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0020_auto_20171124_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='reviewd_times',
            new_name='reviewed_times',
        ),
    ]
