# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0020_auto_20171124_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_content',
            field=models.CharField(default=False, max_length=2000),
        ),
    ]
