# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0021_auto_20171125_0155'),
        ('Tutorial', '0024_auto_20171124_2308'),
    ]

    operations = [
    ]
