# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0026_auto_20171125_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsession',
            name='showname',
            field=models.IntegerField(default=1),
        ),
    ]
